# Generated by Django 4.2.1 on 2023-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdetails',
            field=models.CharField(max_length=100, verbose_name='Product Details'),
        ),
    ]
