# Generated by Django 4.2.1 on 2023-06-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_alter_products_cat_alter_products_pdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'shoes')], verbose_name='Category'),
        ),
    ]
