# Generated by Django 4.2.1 on 2023-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.FloatField(default=0),
        ),
    ]
